spring:
  application:
    name: ai-assistant
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
  openai:
    base-url: https://dashscope.aliyuncs.com/compatible-mode
    api-key: ${OPENAI_API_KEY}
    chat:
      options:
        model: qwen-max-latest # 可选择的模型列表 https://help.aliyun.com/zh/model-studio/getting-started/models
  data:
    redis:
      host: 192.168.52.132
      port: 6379
      password: 154959
      database: 0
      lettuce:
        pool:
          max-idle: 16
          max-active: 32
          min-idle: 8
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug # AI对话的日志级别
    cn.wth.ai: debug  # 本项目的日志级别